- id: typos-conda
  name: typos-conda
  description: 'Source code spell checker, binary install'
  entry: typos
  language: conda
  args: [--force-exclude]
  types: [text]
  stages: [commit, merge-commit, push, manual]
