- id: typos-conda
  name: typos-conda
  description: Source code spell checker, binary install
  language: conda
  entry: typos
  args: []
  types: [text]
  stages: [commit, merge-commit, push, manual]
